CXX = g++-12
CXXFLAGS = -Wall -Wextra
LDFLAGS = -L/home/docker/gmpxx_mkII/i/GMP-6.3.0/lib -lgmp
INCLUDES = -I/home/docker/gmpxx_mkII/i/GMP-6.3.0/include
RPATH_FLAGS = -Wl,-rpath,/home/docker/gmpxx_mkII/i/GMP-6.3.0/lib

TARGET = test_gmpxx_mkII
TARGET_ORIG = test_gmpxx
TARGET_NOPRECCHANGE = test_gmpxx_mkII_noprecchange

SOURCES = test_gmpxx_mkII.cpp
HEADERS = gmpxx_mkII.h
OBJECTS = $(SOURCES:.cpp=.o)
OBJECTS_ORIG = $(SOURCES:.cpp=_orig.o)
OBJECTS_NOPRECCHANGE = $(SOURCES:.cpp=_dontprecchange.o)

all: $(TARGET) $(TARGET_ORIG) $(TARGET_NOPRECCHANGE)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -DGMPXX_MKII -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RPATH_FLAGS)

$(OBJECTS): $(SOURCES) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -DGMPXX_MKII -c $(@:.o=.cpp)

$(TARGET_ORIG): $(OBJECTS_ORIG)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $(TARGET_ORIG) $(OBJECTS_ORIG) $(RPATH_FLAGS) -lgmpxx $(LDFLAGS)

$(OBJECTS_ORIG): $(SOURCES) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $(SOURCES) -o $@

$(TARGET_NOPRECCHANGE): $(OBJECTS_NOPRECCHANGE)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -DGMPXX_MKII -D__GMPXX_MKII_NOPRECCHANGE__ -o $(TARGET_NOPRECCHANGE) $(OBJECTS_NOPRECCHANGE) $(LDFLAGS)

$(OBJECTS_NOPRECCHANGE): $(SOURCES) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -DGMPXX_MKII -D__GMPXX_MKII_NOPRECCHANGE__ -c $(SOURCES) -o $@

clean:
	rm -f $(TARGET) $(TARGET_ORIG) $(TARGET_NOPRECCHANGE) $(OBJECTS) $(OBJECTS_ORIG) $(OBJECTS_NOPRECCHANGE) *~

.PHONY: all clean
